language: python
python:
  - "3.4"
  - "3.5"
sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev libxslt1-dev libtiff5-dev libjpeg8-dev zlib1g-dev
install: "pip install -r requirements/tests.txt"
script: ./manage.py test
